### ISSUE TITLE
Outdated README section for ./install-tools.sh

### ISSUE THREAD

**Issue by Public-Trainsport** [tracelabs/tlosint-vm#39]
Several of the items listed in the git's README under applications are no longer a part of the ./install-tools.sh
I will update this post with the deprecated programs and scripts in the list once I am able.

**Comment by humandecoded** [comment]
Thanks for the catch. If you can list out the missings ones we can get this fixed in the next release. Or feel free to do a PR in to the `dev` branch

**Comment by cblanken** [comment]
@humandecoded 
Hi, I just went through the install myself and the following tools appear to be missing from the `install-tools.sh` script. There are also a few other errors which I've noted.

### Browsers
- Tor Browser

### Data Analysis
- Exifscan (note it seems this repo was made private so I don't know why it still exists in the README)

### Downloaders
- Spiderpig
- WebHTTrack Website Copier (This is in fact installed but is a duplicate of the __Browse Mirrored Websites__ link)

### Email
- Buster
- Infoga (this links yields a 404, so I'm assuming the repo was made private)
- h8mail (this is installed but by default is in `~/.local/bin/h8mail` which isn't added to PATH)

### Frameworks
- OnionSearch (for some reason this links to [PhoneInfoga](https://github.com/sundowndev/phoneinfoga) which also isn't installed). I'm assuming this should be linking to [OnionSearch](https://github.com/megadose/OnionSearch)

### Phone Numbers
- PhoneInfoga (again it's not installed)

### Social Media
- Twayback (this tool is not installed, although according to the maintainer it appears this tool no longer will work as of July 2023 due to changes on the Twitter platform, so it should probably be removed)

### Other Tools
- Sherlock (this is installed but is a duplicate from the Usernames section)

NOTE: Also neither of the archived tools Little Brother or Twint are installed. Is there a reason they're still on the list?
